---
title: "Course Notes"
author: "Ben Marmont"
date: '2022-10-18'
output: html_document
---

# Preparation:
* completed pre-workshop survey
* note there will be 'homework' for after conclusion of the course 
* read 'carpentries 2020 annual report'
* read 'the science of learning'
  
## Carpentries Annual Report Notes:
 * notes verbal and non-verbal biases when teaching and their effects
    * mission (summary):        
        * Increase global data and computational skills used best practice (inclusive, open-access, and evidence based)
    * values: act openly, empower, value all contributions, always learning, people first, access for all, community collaboration, strength through diversity
    * Helped with Glosario, a online global lens glossary of data science terms
    * In 2020 carpentries spent USD$250k on instructor training

## Science of Learning Notes:
  * summary of research from cognitive science about how people learn
    * resource for educators 
    * not a be all and end all for new teachers, but an insight into cognition
    * produced by a non-profit; 'Deans for Impact'
    * Six questions are universal true in teaching, these are how the document is framed
    
 1) _How do students understand new ideas?_
    * students learn new ideas by building on those they already know
      * a sequential curriculum is therefore essential
      * analogies linked ideas are key, but have to be well described
    * information must be moved from short term to long term memory
      * students have limited short term memory
      * if cognitive load is too much learning will stall
      * if multiple communication channels are employed the message must be the same
    * Prequsites should be just that for learning, not age based requirements for content
    
  2) _How do students learn and retain new information?_ 
      * students remember information as it goes in
      * practice is a requirement for learning, but it should be spaced out and interleaved with other practice
    
  3) _How do students solve problems?_
      * subjects areas have sets of facts that underpin everything
       * if these are committed to memeory work-memory is freed up
       * learning by wrote does have its place
     * feedback is essential 
        * good feedback is:
           * specific and clear
           * focused on task, not student
           * focused on improvement not performance
        
  4) _How does learning transfer to new situations in or outside of the classroom?_
      * Problem solving requires understanding the context and structure of a problem
        * teaching background is essential to real-world problem solving 
     * Examples are great for new ideas, but in can be difficult when using different examples
       * teachers can set tasks that have different surfaces but the same underlying structure 
       * can encourage students to label sub-steps where appropriate
       * can substitute word problems with formulas where appropriate
      
  5) _What motivates students to learn?_
    * beliefs about intelligence are important predictors of behaviour at school
      * communicating with students that they can improve their intelligence via learning and feel in control of it 
    * pure interest learning has better long term outcomes that controlled learning  
    * praise and reward should be employed strategically depending on motivations
    * feeling a sense of belonging and acceptanc eimproves academic outcomes
    
  6) _What are the common misconceptions about how students learn and think?_
      * Students do NOT have different learning styles
      * Humans do NOT only use 10% of their brains
      * People do NOT use left/right brain preferentially
      * Novices and experts cannot think in all the same ways
      * Cognitive development should NOT be gatekept by age
         
         
## Preparing presentation
  * 90 second intro early in course
  * 3 minute presentation later in the course
  
90 second intro:
* R is a free, open-source software for (mostly) all things data with a large and growing community
 and extensive packages (free add-ons) for any number of tasks
* before we begin please check you hae R Studio and R installed. The former is an IDE, the later is a console input.
* the first thing we are going to do today is look at inflamation in patients so we will need to import the relevant CSV, ensure that after downloading it you unzip it so that R can read it! 

# Important links
## Etherpad (collaborative notepad)
https://pad.carpentries.org/2022-10-19-online-ttt-NESI
## Schedule for four session workshops
https://murraycadzow.github.io/2022-10-19-online-ttt-NESI/
## Summary of each section
https://carpentries.github.io/instructor-training/reference.html


# Day 1! 

Instructors
* Murray Cadzow
* Mik Black
* Arindam Basu

## Morning session - experience and mental models
Used etherpad for collaboration, a re-skinned google doc 
Three instructor instructors, 2 Otago, one Canterbury. PhDs.
Please keep microphones muted and cameras on.
Etherpad is used extensively for collaboration

Schedule:
  1000 start
  1130 10min break
  1230 45min lunch
  1400 10min break
  3 end

After everyone introduced themselves entirely academic audience.
Types of carpentry workshops:
Software - foundational computational skills
data - effect work with data and its lifecycle
library - library and IT personal focused

Experience levels
* Novice (don't know what they don't know, can't formulate questions)
    * General carpentries attendees
* Competent Practitioner (knows enough to do everyday tasks, even though it may not be right)
* Expert(handles unexpected things well)
The different experience levels can be visualised with different mental models where there are greater connections between concepts as experience increases.

My analogy:
Modelling is like weeds taking over your garden, unless you make an effort to keep it in a given state they will keep growing
  - but you want analogies to be simple and specific with no room for ambiguity
  
Concept maps are a useful tool for lesson planning  

Mental models can easily be constructed differently than intended. Teaching is about fixing mental models.

Formative assessments can be used to correct mental models.
Formative assessments: Useful to teacher and learner, gives learner an idea about their knowledge and gaps.
Summative assessments: Like final exam, assessment of knowledge. No scope for further practice

In formative assessment if answers are spread across all questions it could be a symptom of guessing and studens not having a mental model capable of answering the question. Experts are far better and spotting and solving errors.
 * You need to be very explicit with step by step instructions, especially regarding errors.

Formative assessment is good, but there is a trade off between that and actual content.

Different experience levels like different learning levels, for example, novices can find lots of facts early counterproductive, while expert
  - If people find courses too slow they will be bored, and if its too fast the student won't return. Establishing correct mental models is essential.

Novices don't necessarily have the vocabulary to google solutions to their problems.

We should be careful not use dismissive tones when teaching, for example what may same trivial to us may be lessintuitive to students. For example, instead of saying just open a browser, omitting the 'just' removes the disimissive tone from the sentence.

Asking what questions do you have is phrased more positively than any questions, where the latter has the tone of wanting to moving along quickly.

## Afternoon session - Memory and cognitive load
* What are the limits
* What are the types
* What sort of load do different tasks carry

Memory types:
* Sensory (often discarded, but can train outselves to note them in short and long term memory)
* Short-term
* Long-term

Words from memory task (I got 8/16, yikes! Average is 7-9):
Remembered:
blueberries, strawberriers, croissants, eggs, bacon, milk, tofu, pears
Whole list flashed in front:
milk, bb, donut, strwb, bagel, coffee, pear, tofu, tea,apple, muffin, sausage, bacon, juice, croissants, eggs

People have poor short-term memory when faced with lots of information at once. But there are tools to mitigate this (improve memory retention.)
  * Chunking - grouping words reduces the number of words needed to be committed to memory. 
  * Formative Assessment - using knowledge just received being applied to a task
  * Limiting concepts - as teachers we are drawing on lots of knowledge when teaching, need to abstract from this
  * Group work
  * Opportunities/reflection
  
Cognitive load theory
  * Germane Load (mental effort required to link old and new info in a framework)
  * Intrinsic Load (inherent complexity of the topic)
  * Extraneous Load (everything else) 
  
Guided Practice; Reducing cognitive load:
  * reduce extraneous load
  * manage intrinsic load
  * maximise germane load
  
So the aim  is to maximise learning while reducing cognitive load. 

Attention management techniques:
  * guided practice (faded examples, parsons examples, labelling diagrams)
  * live coding (share code environment, speak commands as you type, build running glossary and command terms)
  
## Feedback  
Surveys are a way to target participants interests and areas. Also informs carpentries databanks, which offers further funding opportunities and keeping the finger on the pulse of coding students.

Timing matters too, formative assessments often and frequent must rapidly follow delivery. Good load is a concept every 15mins with formative assessment.

Minute card (i.e. 1 minute to fill in a feedback card) offer you a way to adjust the workshop on the fly. The minute cards can include prompts.

One-up-One-down: asking people for one positive and negative for the day. May feel unnatural, but normalising feedback is important.

# Day Two 

## Motivation and demoitivation

### Motivation
Peer interaction is a way to increase motivation, AND reduces the workload of instructors/helpers
Ensuring you realise and address confusion maintains motivation
Framing instructors are learners too, helps make you seem as a learner too
Seeing results fast and then deeper learning to understand. For example, when learning R seeing a quick plot can be incredibly rewarding.
For Loops are incredibly useful, and teaching the basics can be quick with quick results. Not a first lesson thing, but could be a signpost for whats to come and be motivating in that way.

### Demotivation
Do not harm 
- Don't talk down to things, even if they are outside of course work i.e. MS Teams
- Don't dive into complex or detailed technical discussions (i.e. if someone asks a deeper question, you can delay it to next break/task)
- Admit when you don't know something (you are an imperfect learner still)
- "Just"
- Take over the learners keyboard. Doesn't help learner, and can be demotivating.
- Show surprise/unawareness (about learners knowledge gaps)

There are two mindsets; fixed and growth. You should encourage the growth mindset, i.e. instead of saying you're not a computer person, you're not a computer person yet.

Errors are essential to learning. They help frame errors positively. 

Using 'yet' helps frame things positively for students.

Praise for effort/improvement is great. In carpentries, praising effort is preferable to improvement.

Sticky notes or some other non-verbal signalling can be useful for learners to communicate with instructors how they are going. For example, green or red when like a traffic light.

Individual questions (group questions are answered on ethernote)
* Why do I teach? Everyone has different backgrounds and motivations, and carpentries embraces this as we all bring unique things to the table.
* I enjoy seeing the penny drop for students, and teaching helps reinforce and develop my own understanding.

## Equity, Inclusion and Accessibility

Defining equity, inclusion and accessibility
* Equality - everyone gets the same, equity - resources are shared based on situation hence is it favourable

Short and more frequent classes can be more accessible for parents, any disability and juggling other commitments.

Accommodation puts the onus of the individual in need, in contrast universal design makes changes for the benefit of everyone.

Accessibility can be improved with simple things like making the font bigger or using a microphone if there is one in the room. Even if the presenter might be comfortable without it it can make it easier for the less-abled.

### Stereotypes and systemic exlcusion
As instructors we should be careful to not call on stereotypes. Stereotyping is demotivating, and may include unnecessary elaborating on something, different treatment to different students etc.

## Teaching is a skill
Japanese 'jugyo kenkyu' is a method of teachers observing,receiving and giving feedback. Feedback can be hard but very useful to becoming a useful teacher.

Feedback has four aspects; content, presentation, positive and negative. Can think of it in a 2x2 rubric.

Feedback is hard, but can be made easier by asking for feedback on specifics but feedback is also a skill (giving and receiving)

After the break we have practice teaching, this will be a short period - next week's sessions will be longer (there are two more after this.)

## Giving and receiving feedback
- 90sec cut off, people give feedback after.
- Feedback given and received including from self
- Take 5mins to make a 90sec presentation, you are not live coding!

### My 90second presentation (for feedback)
What are rmarkdown (.rmd files?)
What is YAML?
How do I use .rmd files?

```
# Backticks like this section specify code

2 * 2
```
_Notes for Me:_

* Positive Content:Visualization,Laid out what to do
* Improve Content:Monotone, No intro text
* Positive Presentation:HTML doc had a lot of other rubbish in it,Steps were clear, good signposting
* Improve Presentation:Show the knit could be useful and different output types,Lack of enthusiasm/monotone

_Notes for Katerina_

* Positive Content:Had scripts to demonstrate and show what we was talking through
* Improve Content:for the 90s prezzie cut script off after data import
* Positive Presentation:Scripts signposted what was next
* Improve Presentation:A lot of umming and pauses, perhaps due to pace?

_Notes for Simon:_

* Positive Content: Really liked the note on utf-8 and macrons for Maori and inclusivity
* Improve Content: More resources to go with screenshot
* Positive Presentation: Welcoming and demonstrated and talked through steps
* Improve Presentation: A lot of mentions of having information sent to them

People tent to struggle giving constructive feedback, but happy to give positive feedback.

There is a homework for next week:
Read up on organising and running workshops
Brain dump of questions about running and planning workshops, so please prepare questions for this
Prepare for live coding 3minutes from a carpentries module
The 3min live coding task is to demonstrate we have learnt something about live coding. Intros are a pad place for this. Don't do the exerercises - its all about the presentation baby!
  - find the lesson you want to teach from, pick a spot with live coding in it 

Relevant links:
https://carpentries.github.io/instructor-training/12-homework/index.html

https://pad.carpentries.org/2022-10-19-online-ttt-NESI#L1367


# Homework ----

Read https://carpentries.github.io/instructor-training/12-homework/index.html
     https://carpentries.org/workshops/#workshop-organising
     https://docs.carpentries.org/topic_folders/hosts_instructors/index.html

## Centrally and Self-Organised workhops
Centrally organised workshops are facilitated by the carpentries administrators. Need to request 2-3 months beforehand. There is an admin fee.

Self-organised workshops are organised by someone reaching out to an instructor who facilitates organisation. No admin fee, but they do ask you submit a form letting them know it is occurring so that instructors get credit and the workshop can be listed online. You can mix and match carpentries curriculum, but it does need to be at the core of the course.

Carpentry workshop requirements
* Teach a lessons core curriculum
* 1+ certified instructor
* uses carpentry curriculum
* use carpentry surveys for evaluations
* abide code of conduct.

Instructors are not paid. Please pay their travel and lodging costs.

## Teaching and Hosting
You are encouraged to run your own workshops.
You can charge whatever you like for workshops, this training is worth money to private industry to charge them lots. But for academics/students accessbility is core to carpentries and therefore fees should not prohibit attendance. 

_Question about organising a workshop_
* can you please elaborate on how charging/fees work? Ideally low cost or no fees to maintain accessibility, but you could charge whatever you want?

# Day Three ----

Had a brief discussion covering general questions in the etherpad about running a workshop (h/w)

## Becoming certified and checking out
There are three tasks to be completed before you become certified.
* Firstly you must make some contribution to one of the lesson repository
* Participate in an online community discussion
* Take part in an online teaching demonstration

Forcing engagement in this way has been a way to preserve and grow the carpentries community.

### Contributions 

Keep it simple, fix a typo, comment on an issue, add a term to a glossary, choose from help wanted (signalled by maintainer needs help.)

Can be anything in data carpentry, library carpentry, software carpentry, incubator or glossario.
Don't stress about something with too much cognitive load. 

GitHub isn't a requirement, you can email the carpentries team if you struggle with it.

### Discussion

There is an Etherpad which has the information about different discussions and their themes.
Each meeting has different time zones attached.

https://pad.carpentries.org/community-discussions#L126

They are not always suitable for NZ tz, but there are many discussions. Occasionally there are carpentries facet-to-face but not often. Participation is the key point.

### Demonstration

There is a rubric of what you will be assessed on.
Five minutes of demonstration (live coding). It is a presentation like format.
Important things are ensuring you use carpentries word and the content you are drawing from.
A lesson is a group of episodes (think modules)
We will chose the lesson, but the examiner will choose the starting point of the lesson.
You can navigate to lessons and see the episodes on the carpentries website
The slots are for an hour and you give and receive feedback from other participants and instructors

You shouldn't have the content on your screen as you teach as it is not good practice. You are welcome to refer to it however!

There are 90 days to complete the checkout process, but these days are relatively soft. They are accommodating and the timeline is to motivate people to complete it.

Make sure you have the requirements ready to go for all episodes in a lesson. That is, you have everything downloaded and dataframes etc created.
These are not tests! It is a collaboration. 

The assessors are not there to trick you, they have been their themselves.

## General notes on carpentries
You can teach slightly different components of the courses, but you need to cover specific parts of the content.

There are non-teaching roles in the wider carpentries communities.

## Rules of workshops
The carpentries modules must be covered and you must have at least one instructor. You do need helpers/co-instructors.

## What is live coding
We don't use slides, instead we code in the environment in live time via a big screen, talking as we go.

We encourage learners to code along with us, making it participatory

Benefits: You can see that issues do occur too and the step by step nature which cannot be addressed in slides.It can reduce the gap between students and instructors. Learned experience.
Disadvantages: Managing screens, managing split attention between what you are doing and what the class is doing or if there are learners needing help.

It is ok to make mistakes, what is important is how we respond to them. Being able to teach something and being an expert is very different. Ultimately we are learners too, and growth mindset is important.

Proper annunciation as you live code can help you slow down your coding to make it easier for learners to follow.

Making sure that text is big enough is important, but students should be aware that their text might look different to mine based off of my preferred set up.

## After Lunch

Watching videos:
https://youtu.be/bXxBeNkKmJE 
https://youtu.be/SkPmwe_WjeY
Content: using the head command in a for loop to see the content of a file.

Standing up and moving around the room (with a mic if possible) makes it easier to consume teaching.

Our live coding should be as similar as possible to students (i.e. colour of text etc) as students will pick up differences. 

TURN OFF NOTIFICATIONS during teaching. One idea is have a seperate account on your laptop which ensures default environments and not connected to accounts.

### Live coding practice

3min presentation, ~1min feedback, one timekeeper, one presenter, one note taker. Hard and fast, not strenuous or in depth feedback. 4 min pp

The four segments of feedback:

Jens::
Positive presentation:
Error of - instead of = was a great learning experience
Good pace and explanation

Positive content:
Great to see you load things in rather than showing code and results.


Improve presentation:
Give a note to google collab which is a google service of python running a jupyter notebook.


Improve content:
Could have files with files in rather than looking in downloads

Katerina: 
Positive Presentation:
Great quick context at the start
Great pace and annunciation

Positive Content:
Great flow I could follow your code and commands easily and they made sense, great to translate the commands into english.
Great to see the slashes

Improve Presentation:
Would be good to talk at the same level about the ls-F as you did for the other commands.

Improve Content:

_Ben feedback:_

Mention when I am running code, or click the run button. <- EXPLAIN THE MAGIC
Mention that outputs are in the console. 

# Preparing to teach
Metacognition is basically thinking about thinking, and is important for learning

There was a note that my headers signposting what was coming was useful but might cause people to read ahead.

Set checkpoints to check that people have learned/achieved an objective i.e. formative assessment. "Do you understand?" is not a formative assessment, a targetted formative assessment is a way to assess whether people have learned it.

Be prepared to cut the course material in order to ensure breaks happen on time etc. But, watch out for dependencies and offer wrap up time, but also don't speed up to make time. Communicate team and learners what you will omit and how it can be researched later.

Review instructor notes on lessons before the course, these are the gems of all the contributors whom have gone before.  

Revisiting previous feedback can be of use also.

To teach effectively you need to know who you are teaching, and think about how learning objectives can be tailored and achieved specifically for the learners.

Don't stress about finishing content, finish what you finish.

There is more content in the episodes what what the time it alotted.

# Day Four
## Minute notes response
Etherpad starts 1944
https://pad.carpentries.org/2022-10-19-online-ttt-NESI#L1944
The etherpad and the website will endure after the course. All links from course are in the bottom of the etherpad.

You can be as engaged as you want, but establishing connections in the community could be valuable to your career. Just make sure you fulfill checkout obligations.

Regarding demonstration, move at appropriate teaching place don't worry about where you get to in the material and feel free to refer to post it notes to signal understanding like you would in a real class.

## Live coding round two
Turn around of 5 minutes (3 min presentation, fast feedback)

Feedback for me:
Be careful of the use of 'c to create a list' which is another data type.
Scrolling lots between steps can help learners follow what has been happening. 

For demonstration practice picking a random point, skimming through it and 'live coding.' Familiarising yourself with the material aid your confidence when demonstrating. 

You can get informal feedback, or formal feedback.

Also can ask learners if text is big enough etc.

## Working with your team
* never teach alone
* the team can consist of c(host, instructors, or helpers)
* classroom practice
    - start with code of conduct
    - hands off help (participants should do things)
    - learners use their own machines (so learners can replicate on their machine later)
    - sticky notes and formative assessments to maintain touchpoints
    - breaks (essential for maintaining participation)
    - team teach/teach and assist (one person teaches on screen, the other roams)
    
You should communicate with your team, especially if they are not Carpentries certified instructures to ensure that you are on the same page about the content you will cover. I.e. not differentiating too much from the course content so that learners are not confused.    

If you are unsure about Code of Conduct infractions you can contact a 24/7 Carpentries team which are able to investigate where investigations are not something we need to do.

The carpentries will support your descision, be it cancelling the workshop, excluding the student or something less severe.

If you make a workshop and website ensure that you include the main branch and have repo public.

Murray Cadzow offered to help create a website if we are struggling with it.

## What is an introduction?
How to start and end a workshop

### Setting the stage
* Make sure you have the attire sufficient for the role and organisation. It is easier to start formal and down-dress as cllothing signals skills. 
* Physical environment - how is the class arrange? Size of room and number of learners
* Virtual environment - Do you have a waiting room or a slide. 
* Pre-class moments - You should be the first person there not in a rush setting things up. 

### Instructor and helper introductions
* think about hows these people will introduce themselves (somethings can remain unsaid i.e. your inexeperience)
* some sort of icebreaker can be of use

### Workshop 101
* be upfront about what you are offering
* share schedule, logisitics and structure
* communicate expectations (we want engagement and participation)
* advice for success
* whet appetite for workshop (encourage excitement in group) i.e. at the end of today you will be able to make this plot (if doing an R tutorial) 

### Practicing your introduction
Draft a 5 min introduction, then present to breakout members and present to them and give feedback.

Notes for my introduction:
Name and background (masters student at UoW studying methane mitigation in the diary industry under the umberlla term of environmental economics)

Today we are covering R for Reproducible Scientific Analysis, which assumes that you have some existing knowledge of R and want to deepen your understanding. Prereqs are understanding programs, scripts and data. OK if not R expert.

Not a statistical course

Good to know what you are going to say in your introduction because unlike your course material it is not mapped out and you can cover a lot of introduction material in a short period of time (unlike material which is SLOOOOOW)
* bullet points for these things would be great for me as a presenter

## Making a smooth landing
Make sure you stop early to allow reflection and people to finish on time. Offer people the links/knowledge to find the rest of the content not covered. There is a lot of content in any given lesson, don't worry if you cannot address them all.

Telling people what to do with their scripts at the end can be useful, i.e. saving scripts and closing R.

Jens raised the question of if there is something you can put on LinkedIn, Murray will investigate this.

One up, one down at the end
* Good: Use of breakout
* Improve: More signposting (I know there is a schedule but a lot of windows to juggle)